### PR TITLE
Query Fix

### LINKED ISSUE #48: Change SQL result object to remove field data
Right now a lot of our codebase uses samples such as the one below.

```js
var results = await query('SELECT * FROM something');
```

What this does is actually return an array with our results[] inside of it, along with our field data. We don't want this, and this can cause some issues when checking if results.length > 0 (which it always will be).

We need to change all occurences to
```js
var [results] = await query('SELECT * FROM something');
```
So we strip the extra data we don't want, preventing some headaches in the future.

### PR DESCRIPTION
**Pull request by Raghuboi**
closes #48

### CODE REVIEW

File: web/pages/api/auth/signin/index.js [hunk 1]
```diff
@@ -9,21 +9,16 @@ const handler = nextConnect().post(async (req, res) => {
...
       [email]
-    );
-
-    if (results[0].length < 1)
-      res.status(401).json({ error: "Email not found" });
-    else results = JSON.parse(JSON.stringify(results[0][0])); // this is needed to parse the RowPacket that mysql returns
-
-    const { password: hashedPW, id } = results;
+    );    
+    if (results.length < 1) res.status(401).json({ error: "Email not found" });
```
Comment (xTrig) [inline web/pages/api/auth/signin/index.js:18]: Good for debug! We need to note later to change these messages to not giveaway these details.

It's standard security to reject all logins with the same message, so that an 'attacker' doesn't get free information like "hey this email exists, but I got the password wrong."

**Review by xTrig — APPROVED** [review]

File: web/pages/api/auth/signin/index.js (hunk 1 above)
Comment (Raghuboi) [reply web/pages/api/auth/signin/index.js:18]: Never thought about it that way, makes sense
